### ISSUE TITLE
[admin/models] Implement nested subnets

### ISSUE THREAD

**Issue by nemesifier** [openwisp/django-ipam#21]
@hispanico what is the purpose of the master subnet field?

Right now I think the current implementation doesn't really do much with it, infact I can select pretty much any rubbish value and the system will accept it. Implementing this correctly will take effort because we'll also probably need to have any subnet which is flagged as master (by another subnet) to show part of its address space occupied.

I suggest removing it temporarily and discuss of how it should be properly implemented.

**Comment by nemesifier** [comment]
I'd say just remove `master_subnet` and all its related logic because we don't have time to implement this right now, we need to hurry up to implement #19, #17 and #10 and move on to integrate this module with the rest of OpenWISP 2.

**Comment by hispanico** [comment]
I'm totally agree, the master subnet with nested subnets cloud be implemented in the future.

**Comment by nemesifier** [comment]
@hispanico shall we start defining how to implement this feature?

- what happens if a user tries to create a new subnet which is part of an existing subnet? Does the system propose to make the new subnet a child of the parent subnet? 
- how does the visualization of address allocation take master subnets into account?
- how does the visualization of address allocation take children subnets into account?

**Comment by anurag-ks** [comment]
The python's ipaddress module provides some helpful functions, like `subnet_of`, `supernet`, etc. which we can use while implementing nested subnet feature.
Source - https://docs.python.org/3/library/ipaddress.html#ip-network-definitions

**Comment by hispanico** [comment]
> what happens if a user tries to create a new subnet which is part of an existing subnet? Does the system propose to make the new subnet a child of the parent subnet?

The system should be show  a message to explain the issue:
- Subnet overlaps
![image](https://user-images.githubusercontent.com/3329032/42753246-91a86174-88f0-11e8-9e35-080d585e3dfe.png)
- Nested subnet not in root subnet
![image](https://user-images.githubusercontent.com/3329032/42753269-a5218e92-88f0-11e8-8dff-11ce4b0be927.png)

> how does the visualization of address allocation take master subnets into account?

When a subnet has at least one nested subnet, the visualization should be only the nested subnets, because we cannot add IP address into the master subnet .
![image](https://user-images.githubusercontent.com/3329032/42752807-5675e56e-88ef-11e8-9c26-258ea2a78c1d.png)

If a nested subnet has been created in a master subnet with IP address already the visualization should be somting like this:
![image](https://user-images.githubusercontent.com/3329032/42753087-183bac88-88f0-11e8-86c2-165e34186903.png)

> how does the visualization of address allocation take children subnets into account?

Linke the current one for the IP address with a Hierarchy field
![image](https://user-images.githubusercontent.com/3329032/42753157-45b2c5e8-88f0-11e8-89e0-bb316e2a5b59.png)


Maybe we can create a drop-down menu with the availeble nested subnets up to the prefix /24: 
![image](https://user-images.githubusercontent.com/3329032/42752148-4c69aa9e-88ed-11e8-9b8e-14873b35b62d.png)

**Comment by anurag-ks** [comment]
@nemesisdesign @hispanico  the subnet and master subnet validation checks are done on my local branch, but I am not sure about the visualizations, how do they work in case of master subnet and subnets, could explain a bit more?

**Comment by hispanico** [comment]
The master subnet view, in case of nested subnets, shows the child subnets instead of the ip address.
See the following image:
![image](https://user-images.githubusercontent.com/3329032/44004659-142df098-9e66-11e8-83af-d32f12d44eb0.png)

**Comment by atb00ker** [comment]
**Update:**
Implemented the hierarchical network view for subnets.
Implementing the same for IPv6, please review and suggest accordingly. :smile: 
![yay](https://user-images.githubusercontent.com/24985760/50658162-7a34e300-0fbe-11e9-8c10-6cc287e67ecc.png)

**Comment by nemesifier** [comment]
@atb00ker that looks great! Is a PR already open for that?

**Comment by nemesifier** [comment]
AFAIK this can be closed.
