### ISSUE TITLE
[travis] segmentation fault 

### ISSUE THREAD

**Issue by DaffyTheDuck** [openwisp/django-ipam#81]
while updating dependencies and django(2.2), error occurs in travis-ci `coverage run --source=django_ipam runtests.py" exited with 139.` Which is a **Segmentation fault.**. After searchig for the fix, I found that this error could be related to SQLite3..

* The travis-ci error : https://travis-ci.org/openwisp/django-ipam/builds/617307974?utm_source=github_status&utm_medium=notification

* Issue : https://github.com/openwisp/django-ipam/issues/78

I also found that this error can be skipped by specifying the distribution version in .travis.yml

* Passing when dist is specified : https://travis-ci.org/openwisp/django-ipam/jobs/619174470?utm_medium=notification&utm_source=github_status

Thank You :smile:

**Comment by pandafy** [comment]
I checked with distribution set to Trusty and it passed as well. [Travis logs for Trusty](https://travis-ci.com/TheOneAboveAllTitan/django-ipam/builds/138774994)

SQLite version installed for Trusty is 3.8.2, which can be checked in [Travis logs here](https://travis-ci.com/TheOneAboveAllTitan/django-ipam/jobs/261762765#L463)

**Comment by nemesifier** [comment]
This issue is still not resolve, I created a Google Code-In task for it: `[ipam] Fix segmentation fault in travis build`.

**Comment by DaffyTheDuck** [comment]
Okay :smile:

**Comment by DaffyTheDuck** [comment]
Hmm, there's temporary fix available 

Okay :smiley: 

Sorry for closing it :smiley:

**Comment by waleko** [comment]
I guess, I know what causes the segmentation fault. I debugged the code and found, that exception is being raised deep in sqlite backend when it rollbacks to some previous sql savepoint (doesn't actually matter, but it happens in [test_admin.test_subnet_popup_response](https://github.com/openwisp/django-ipam/blob/master/django_ipam/tests/base/test_admin.py#L68)).

I found the exact same [issue](https://www.sqlite.org/src/info/7f7f8026eda38) on sqlite3 bug tracker. It's been fixed in version 3.12.1 ([changelog](https://www.sqlite.org/changes.html)). It so happens, that latest sqlite3 package version for xenial is only 3.11 ([package info](https://packages.ubuntu.com/xenial/sqlite3)), so xenial builds just don't have a patch for it.

This means, that solution by just setting dist to bionic is perhaps actually the right one.

**Comment by atb00ker** [comment]
@waleko Great research work. 
Have you taken this in GCI?

**Comment by waleko** [comment]
@atb00ker Yes, I have
